# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AiCli < Formula
  desc "TUI assistant for shell commands via LLM"
  homepage "https://github.com/karpulix/ai-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/karpulix/ai-cli/releases/download/v0.1.0/ai-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "78355cea95fa88781e7553afb354430dfe1925c2f4f1cc7da68235b1c3f16435"

      define_method(:install) do
        bin.install "ai-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/karpulix/ai-cli/releases/download/v0.1.0/ai-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "b691a3f5e4295042952c3ca16686eefa7c8594fd539136a2dce2303c72fefb36"

      define_method(:install) do
        bin.install "ai-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/karpulix/ai-cli/releases/download/v0.1.0/ai-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "c87af3418725f5df9fa96ce1b509fffc3b430df22e631204662a80088d0e5d81"
      define_method(:install) do
        bin.install "ai-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/karpulix/ai-cli/releases/download/v0.1.0/ai-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "d817edfe7fde593cd54b5f8ccf27a9c9c506da6f408ac8d00af767bf53c83b34"
      define_method(:install) do
        bin.install "ai-cli"
      end
    end
  end

  test do
    system "#{bin}/ai-cli", "--version"
  end
end
