# This file was generated by GoReleaser. DO NOT EDIT.
cask "ai-cli" do
  desc "TUI assistant for shell commands via LLM"
  homepage "https://github.com/karpulix/ai-cli"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ai-cli"

  on_macos do
    on_intel do
      url "https://github.com/karpulix/ai-cli/releases/download/v0.1.2/ai-cli_0.1.2_darwin_amd64.tar.gz",
        verified: "github.com/karpulix/ai-cli/releases/download"
      sha256 "cfba27651e78a2b988b6f466f966cbd5154bd4dd87a7cf940bdf3d7eeab1e233"
    end
    on_arm do
      url "https://github.com/karpulix/ai-cli/releases/download/v0.1.2/ai-cli_0.1.2_darwin_arm64.tar.gz",
        verified: "github.com/karpulix/ai-cli/releases/download"
      sha256 "cd24752c351f151dc82ab7876407a389309321477371abb10b36faca2a5e0e23"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/karpulix/ai-cli/releases/download/v0.1.2/ai-cli_0.1.2_linux_amd64.tar.gz",
        verified: "github.com/karpulix/ai-cli/releases/download"
      sha256 "12dd4fe74639b1731d692bc7b92768c7dc5490f8017ae7b9e02f587dd48e9a7b"
    end
    on_arm do
      url "https://github.com/karpulix/ai-cli/releases/download/v0.1.2/ai-cli_0.1.2_linux_arm64.tar.gz",
        verified: "github.com/karpulix/ai-cli/releases/download"
      sha256 "4e2ddde9dbc8eabab6d71d3b1340bbbfa1cdab9b8f92899934840c073b9982cb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ai-cli"]
    end
  end

  # No zap stanza required
end
